### ISSUE TITLE
Inquiry for workflow

### ISSUE THREAD

**Issue by flamendless** [EngineerSmith/Runtime-TextureAtlas#4]
Hi, im currently looking for a tool that i can use to create atlas textures that can also export accompanying data format for accessing said sub images in the atlas like in free-tex-packer online tool.

I see that the purpose of this tool is for runtime usage but im wondering if you have plans to support making it usable as a step in workflow for a more complex project? Maybe like usable with a shell script that can run this lib to get images in a folder and export the atlas with data (json/lua table).

**Comment by EngineerSmith** [comment]
That would be interesting to do something like that, but I would have to create a new repository and this would be a dependency. Then it can be isolated for the additional code needed, and work with any updates that this repository gets.

I could get something like this going in 3-4 days in my spare time, but it will be a love project and so, the biggest problem I can see encountering is the issue with love's file system. It is only able to only write and read within it's own virtual filesystem. You could use a shell script to get it to move files around for you, but that would come with the maintenance to pull the correct file path to the files causing a duplication of assets (say, you was on a build machine with limited memory and a lot of images, it could cause an issue). Otherwise, I personally like JSONs than Lua tables, due the fact malicious functions cannot be included in them. 

So yes, I could do it if you could tell me how you would want the input/output of the files to work, so that it works with love's virtual filesystem on all platforms. So far, I can only think of 2 arguments, `buildAtlas.sh -input <dir> -output <dir>`

Edit: Excluded maxSize argument, as you can't create an image bigger than the limits on that (build) machine.

**Comment by flamendless** [comment]
I suggest using this for the filesystem issue https://github.com/zorggn/nativefs

For the exported data maybe allow a custom API that can allow user to freely structure the output data? Look at https://free-tex-packer.com/app , there's a custom export option where user can provide a template 🤔
Heres what my custom export data for lua looks like:
```
local Data = {
	frames = {
		{{#rects}}
		{{{name}}} = {
			frame = {
				x = {{frame.x}},
				y = {{frame.y}},
				w = {{frame.w}},
				h = {{frame.h}}
			},
			rotated = {{rotated}},
			trimmed = {{trimmed}},
			spriteSourceSize = {
				x = {{spriteSourceSize.x}},
				y = {{spriteSourceSize.y}},
				w = {{spriteSourceSize.w}},
				h = {{spriteSourceSize.h}}
			},
			sourceSize = {
				w = {{sourceSize.w}},
				h = {{sourceSize.h}}
			},
			pivot = {
				x = 0.5,
				y = 0.5
			}
		}{{^last}},{{/last}}
		{{/rects}}
	},
	meta = {
		app = "{{{appInfo.url}}}",
		version = "{{appInfo.version}}",
		image = "{{config.imageFile}}",
		format = "{{config.format}}",
		size = {
			w = {{config.imageWidth}},
			h = {{config.imageHeight}}
		},
		scale = {{config.scale}}
	}
}
return Data
```


For the usage i like your sample one. But if using the above code for filesystem, then i guess just 
```
lua buildAtlas.lua input_dir output_dir -c custom_template -other options
```
would suffice, shell script or lua whichever. 

Possible options (referencing free-tex-packer) would be:
* Padding size
* Extrude
* Power of two
* No extension

**Comment by EngineerSmith** [comment]
I've started on it [here](https://github.com/EngineerSmith/Export-TextureAtlas)

**Comment by flamendless** [comment]
Yup, saw it already and starred it.

**Comment by EngineerSmith** [comment]
I can't figure out what Power of two does on free-tex-packer. It seems to just add an extra column that is wasted space on my tests, or it changed the atlas from being horizontal to vertical. I managed to use the same library for the templating, so it should be similar syntax to what you're used to - just less variables to put into it.
Open an issue on that repo if there is something broke, or to suggested feature I've missed, or a variable you would like to see in the template (default template covers all the available variables).

**Comment by flamendless** [comment]
Power of two keeps the texture size in powers of two like 256, 512, 1024, 2048, and so on like perfectly divisible by two to avoid texture bleeding in technicalities i don't know 100 percent but was informed by others before. It's just for a good measure. 

You made it within a short amount of time, awesome. I'll try and integrate it into my workflow and test it. I'll let you know if there's any issue with it

**Comment by EngineerSmith** [comment]
I've looked into it lightly (a couple googles). I have also heard about it before, but it was mostly because old graphics cards (and old smartphones) only supported pow2 textures. Internally, they will fix this issue themselves by linear interpolation. You can set the behaviour in love on how it creates mipmaps using `Texture:setMipmapFilter`

I can implement it, but I don't know how much additional wasted space it will add on to your texture as the packing algorithms haven't been designed to pack towards a particular side. E.g. A resulting pack could return 16x1025 (just above 1024 cut off) and then have to extend it to 2048, wasting 16x2023 pixels of space (and memory depending on encoding). I'll add it in, and put the warning on the documentation for now, so use it at your own risk.

**Comment by EngineerSmith** [comment]
I just implemented it, and from my test data it doesn't increase file size too much. Without the argument it creates the atlas at 265x18 for 4.77KBs, and with the argument it creates the atlas at 512x32 for 4.99KBs. So it wasn't as big of an issue as I thought it would be for the resulting encoded PNG.
![atlas](https://user-images.githubusercontent.com/56016593/143609495-1c4bb34f-2361-403e-b5e8-df3afec725e9.png)
becomes
![atlasPow2](https://user-images.githubusercontent.com/56016593/143609501-7707a2c0-3b03-4a6e-ae65-36eede0cd73b.png)
(Using `-extrude 1` and `-padding 1` for both)
